In [2]:
from checkmybus import CheckMyBusClient, CheckMyBusSearchParams

In [12]:
client = CheckMyBusClient()
result = client.search(CheckMyBusSearchParams(
    departure_location="Munich, Germany",
    departure_date="2026-05-10",
    arrival_location="Nuremberg, Germany",
))

In [13]:
df = result.to_dataframe()

In [14]:
df.tail()

,company,operator,origin_city,origin_station,dest_city,dest_station,departure_dt,arrival_dt,duration_min,duration_str,...,currency,price_formatted,transport_mode,stops,free_seats,seat_class,sold_out,deep_link,checkmybus_url,source
124,Deutsche Bahn,Deutsche Bahn,Munich,East Station,Erlangen,Central Station,2026-05-10 00:49:00,2026-05-10 06:55:00,366,6h 6m,...,EUR,€29.19,train,2,50,Economy,False,None,https://www.checkmybus.com/munich/nuremberg?mo...,checkmybus
125,Deutsche Bahn,Deutsche Bahn,Munich,East Station,Erlangen,Central Station,2026-05-10 21:07:00,2026-05-11 00:26:00,199,3h 19m,...,EUR,€29.19,train,2,50,Economy,False,None,https://www.checkmybus.com/munich/nuremberg?mo...,checkmybus
126,Deutsche Bahn,Deutsche Bahn,Munich,East Station,Erlangen,Central Station,2026-05-10 22:09:00,2026-05-11 01:39:00,210,3h 30m,...,EUR,€19.19,train,1,50,Economy,False,None,https://www.checkmybus.com/munich/nuremberg?mo...,checkmybus
127,FlixBus,FlixBus,Munich,Central Bus Station,Fuerth,Central Station,2026-05-10 02:00:00,2026-05-10 04:10:00,130,2h 10m,...,EUR,€14.98,bus,0,73,Economy,False,None,https://www.checkmybus.com/munich/nuremberg?mo...,checkmybus
128,BlaBlaCar,BlaBlaCar,Munich,Pelkovenstraße 91,Nuremberg,Parkplatz TuT,2026-05-10 13:00:00,2026-05-10 14:50:00,110,1h 50m,...,EUR,€12.29,car,0,50,Economy,False,None,https://www.checkmybus.com/munich/nuremberg?mo...,checkmybus

In [6]:
df[df['transport_mode']=="train"]

,company,operator,origin_city,origin_station,dest_city,dest_station,departure_dt,arrival_dt,duration_min,duration_str,...,currency,price_formatted,transport_mode,stops,free_seats,seat_class,sold_out,deep_link,checkmybus_url,source
0,Deutsche Bahn,Deutsche Bahn,Munich,Central Station,Frankfurt am Main,Central Station,2026-05-16 00:01:00,2026-05-16 04:38:00,277,4h 37m,...,EUR,€27.99,train,0,50,First Class,False,None,https://www.checkmybus.com/munich/frankfurt-am...,checkmybus
1,Deutsche Bahn,Deutsche Bahn,Munich,Central Station,Frankfurt am Main,Central Station,2026-05-16 00:01:00,2026-05-16 04:38:00,277,4h 37m,...,EUR,€17.99,train,0,50,Economy,False,None,https://www.checkmybus.com/munich/frankfurt-am...,checkmybus
2,Deutsche Bahn,Deutsche Bahn,Munich,Central Station,Frankfurt am Main,Central Station,2026-05-16 01:59:00,2026-05-16 07:37:00,338,5h 38m,...,EUR,€40.99,train,2,50,First Class,False,None,https://www.checkmybus.com/munich/frankfurt-am...,checkmybus
3,Deutsche Bahn,Deutsche Bahn,Munich,Central Station,Frankfurt am Main,Central Station,2026-05-16 01:59:00,2026-05-16 07:37:00,338,5h 38m,...,EUR,€29.99,train,2,50,Economy,False,None,https://www.checkmybus.com/munich/frankfurt-am...,checkmybus
4,Deutsche Bahn,Deutsche Bahn,Munich,Central Station,Frankfurt am Main,Central Station,2026-05-16 04:20:00,2026-05-16 07:40:00,200,3h 20m,...,EUR,€29.99,train,1,50,First Class,False,None,https://www.checkmybus.com/munich/frankfurt-am...,checkmybus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,Deutsche Bahn,Deutsche Bahn,Munich,Central Station,Frankfurt am Main,South Station,2026-05-16 06:44:00,2026-05-16 10:23:00,219,3h 39m,...,EUR,€37.99,train,1,50,Economy,False,None,https://www.checkmybus.com/munich/frankfurt-am...,checkmybus
124,Deutsche Bahn,Deutsche Bahn,Munich,Central Station,Frankfurt am Main,South Station,2026-05-16 10:19:00,2026-05-16 13:55:00,216,3h 36m,...,EUR,€39.94,train,2,50,Economy,False,None,https://www.checkmybus.com/munich/frankfurt-am...,checkmybus
125,Deutsche Bahn,Deutsche Bahn,Munich,Central Station,Frankfurt am Main,South Station,2026-05-16 19:45:00,2026-05-16 23:04:00,199,3h 19m,...,EUR,€78.99,train,1,50,First Class,False,None,https://www.checkmybus.com/munich/frankfurt-am...,checkmybus
126,Deutsche Bahn,Deutsche Bahn,Munich,Central Station,Frankfurt am Main,South Station,2026-05-16 19:45:00,2026-05-16 23:04:00,199,3h 19m,...,EUR,€67.99,train,1,50,Economy,False,None,https://www.checkmybus.com/munich/frankfurt-am...,checkmybus
127,Deutsche Bahn,Deutsche Bahn,Munich,Central Station,Frankfurt am Main,South Station,2026-05-16 19:45:00,2026-05-16 23:04:00,199,3h 19m,...,EUR,€67.99,train,1,50,Economy,False,None,https://www.checkmybus.com/munich/frankfurt-am...,checkmybus

In [29]:
df["transport_mode"].unique()

<StringArray>
['bus']
Length: 1, dtype: str

In [30]:
df

,company,operator,origin_city,origin_station,dest_city,dest_station,departure_dt,arrival_dt,duration_min,duration_str,...,currency,price_formatted,transport_mode,stops,free_seats,seat_class,sold_out,deep_link,checkmybus_url,source
0,FlixBus,FlixBus,Munich,Central Bus Station,Venice Airport,Venice Airport,2026-04-16 03:05:00,2026-04-16 13:45:00,640,10h 40m,...,EUR,€42.47,bus,1,62,Economy,False,None,https://www.checkmybus.com/munich/venice-airpo...,checkmybus
1,FlixBus,FlixBus,Munich,Central Bus Station,Venice Airport,Venice Airport,2026-04-16 08:00:00,2026-04-16 17:15:00,555,9h 15m,...,EUR,€30.98,bus,0,70,Economy,False,None,https://www.checkmybus.com/munich/venice-airpo...,checkmybus
2,FlixBus,FlixBus,Munich,Central Bus Station,Venice Airport,Venice Airport,2026-04-16 13:45:00,2026-04-16 23:55:00,610,10h 10m,...,EUR,€42.47,bus,1,35,Economy,False,None,https://www.checkmybus.com/munich/venice-airpo...,checkmybus
3,FlixBus,FlixBus,Munich,Central Bus Station,Venice Airport,Venice Airport,2026-04-16 23:15:00,2026-04-17 07:40:00,505,8h 25m,...,EUR,€41.98,bus,0,50,Economy,False,None,https://www.checkmybus.com/munich/venice-airpo...,checkmybus
4,FlixBus,FlixBus,Munich,Central Bus Station,Pitomača,Ul. Ljudevita Gaja,2026-04-16 23:40:00,2026-04-17 10:35:00,655,10h 55m,...,EUR,€31.98,bus,0,67,Economy,False,None,https://www.checkmybus.com/munich/venice-airpo...,checkmybus